_target_: loaders.speechcommands.SCLoader

sample_rate: 16000
batch_size: 512

feature:
  _target_: torchaudio.transforms.MFCC
  n_mfcc: 13
  sample_rate: 16000
  melkwargs:
    n_mels: 64
    n_fft: 400 # n_fft/win_len
    norm: null
    hop_length: 256 # hop_len
    center: False
  log_mels: True
